### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by HSGamer** [etases/EduBlock.Report#1]
# Description
Complete the final report to finish the system

# Tasks
* [ ] User Guide
* [ ] SRS-related
  * [ ] Scope
  * [ ] Limitations
  * [ ] Business Rules
  * [ ] Assumptions
  * [ ] Requirements
    * [ ] Functional Requirements
    * [ ] Non-functional Requirements
    * [ ] Other Requirements
  * [ ] Use cases
* [ ] Management Plan
  * [ ] WBS
  * [ ] Tools
* [ ] Diagrams
  * [ ] Architecture
  * [ ] Workflow
  * [ ] Swim lane
  * [ ] ERD (auto-generated)
  * [ ] Component
* [ ] Test
  * [ ] Cases
  * [ ] Reports
* [ ] Screenshots
* [ ] Demo video
* [ ] Complete Report

# Note
* Use [PlantUML](https://plantuml.com/) for diagrams
* May require the system to finish

**Comment by HSGamer** [comment]
- [ ] Project Introduction @AhnUy 
- [ ] Project Management @HSGamer 
- [ ] SRS @khoinguyen26

**Comment by HSGamer** [comment]
* [ ] User Guide @tunbk1002

**Comment by HSGamer** [comment]
* [ ] Test Doc @khoatvbattu
